config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  get "up" => "rails/health#show", as: :rails_health_check

  resources :dogs, only: [:index, :show]
  resources :training_sessions
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  trainer_id :bigint           not null
#
# Indexes
#
#  index_dogs_on_trainer_id  (trainer_id)
#
# Foreign Keys
#
#  fk_rails_...  (trainer_id => trainers.id)
#
class Dog < ApplicationRecord
  belongs_to :trainer
  has_many :training_sessions
  before_create ->(dog) { dog.slug = dog.name.downcase.gsub(/[^\w\d\s]/, "").gsub(/\s/u, "-") }

  def to_param
    slug
  end
end

app/models/trainer.rb
# == Schema Information
#
# Table name: trainers
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_trainers_on_email                 (email) UNIQUE
#  index_trainers_on_reset_password_token  (reset_password_token) UNIQUE
#
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs
  has_many :training_step_templates
end

app/models/training_session.rb
# == Schema Information
#
# Table name: training_sessions
#
#  id              :bigint           not null, primary key
#  completed_at    :datetime
#  longest_absence :integer
#  rating          :integer
#  started_at      :datetime
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  dog_id          :bigint           not null
#  trainer_id      :bigint           not null
#
# Indexes
#
#  index_training_sessions_on_dog_id      (dog_id)
#  index_training_sessions_on_trainer_id  (trainer_id)
#
# Foreign Keys
#
#  fk_rails_...  (dog_id => dogs.id)
#  fk_rails_...  (trainer_id => trainers.id)
#
class TrainingSession < ApplicationRecord
  belongs_to :trainer
  belongs_to :dog
  has_many :training_steps
  accepts_nested_attributes_for :training_steps, reject_if: lambda { |attributes| attributes['description'].blank? }

end

app/models/training_step.rb
# == Schema Information
#
# Table name: training_steps
#
#  id                  :bigint           not null, primary key
#  description         :text(65535)
#  notes               :text(65535)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  training_session_id :bigint           not null
#
# Indexes
#
#  index_training_steps_on_training_session_id  (training_session_id)
#
# Foreign Keys
#
#  fk_rails_...  (training_session_id => training_sessions.id)
#
class TrainingStep < ApplicationRecord
  belongs_to :training_session
end

app/models/training_step_template.rb
# == Schema Information
#
# Table name: training_step_templates
#
#  id          :bigint           not null, primary key
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  trainer_id  :bigint
#
# Indexes
#
#  index_training_step_templates_on_trainer_id  (trainer_id)
#
class TrainingStepTemplate < ApplicationRecord
  belongs_to :trainer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_trainer!
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = current_trainer.dogs
  end

  def show
    @dog = current_trainer.dogs.find_by(slug: params[:id])
    @training_sessions = @dog.training_sessions
  end

  # TODO: create, edit, delete
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_trainer!
  def index
  end
end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  def index
    @training_sessions = TrainingSession.where(trainer_id: current_trainer.id)
  end

  def new
    unless params[:dog_name]
      flash[:notice] = "Dog not found!"
      redirect_to dogs_path
    end

    @dog = current_trainer.dogs.find_by(name: params[:dog_name])
    @training_session = TrainingSession.new
    2.times { @training_session.training_steps.build }
  end

  def create
    dog = current_trainer.dogs.find(training_session_params["dog_id"])
    unless dog
      flash[:error] = "Dog not found!"
      redirect_to new_training_session_path
    end
    training_session = dog.training_sessions.new(training_session_params.merge(trainer_id: current_trainer.id))
    if training_session.save
      training_session.save
      redirect_to training_sessions_path
    else
      render "new"
    end
  end

  def show
    @training_session = TrainingSession.where(id: params[:id], trainer_id: current_trainer.id).first
  end

  private

  def training_session_params
    params.require(:training_session).permit(:dog_id, training_steps_attributes: [:id, :description])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dogs/index.html.erb
<div class="relative rounded-xl overflow-x-auto shadow-md sm:rounded-lg w-auto">
  <table class="min-w-full">
    <thead class="bg-gray-50">
      <tr>
        <th class="py-4">Name</th>
        <th class="py-4"></th>
        <th class="py-4"></th>
      </tr>
    </thead>
    <% @dogs.each do |dog| %>
      <tr class="odd:bg-white even:bg-gray-50">
        <td class="py-4 text-center"><%= dog.name %></td>
        <td class="py-4 text-center font-bold hover:underline"><%= link_to "Details", dog_path(dog) %></td>
        <td class="py-4 text-center font-bold hover:underline"><%= link_to "+ Create Training Session", new_training_session_path(dog_name: dog.name) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/dogs/show.html.erb
<h1 class="text-5xl mb-6"><%= @dog.name %></h1>
<h2 class="text-2xl mb-4">Training Sessions</h2>
<div class="relative rounded-xl overflow-x-auto shadow-md sm:rounded-lg w-auto">
  <table class="min-w-full">
    <thead class="bg-gray-50">
      <tr>
        <th class="py-4">Started At</th>
        <th class="py-4">Completed At</th>
        <th class="py-4">Rating</th>
        <th class="py-4">Longest Absence</th>
        <th class="py-4">Steps</th>
      </tr>
    </thead>
  <% @training_sessions.each do |training_session| %>
    <tr class="odd:bg-white even:bg-gray-50">
      <td class="py-4 text-center"><%= training_session.started_at %></td>
      <td class="py-4 text-center"><%= training_session.completed_at %></td>
      <td class="py-4 text-center"><%= training_session.rating %></td>
      <td class="py-4 text-center"><%= training_session.longest_absence %></td>
      <td class="p-4 text-center">
        <ul>
        <% training_session.training_steps.collect do |tst| %>
          <li><%= tst.description %></li>
        <% end %>
        </ul>
      </td>
    </tr>
  <% end %>
  </table>
</div>
<p class="mt-6">
  <%= link_to "+ Create new Training Session", new_training_session_path(dog_name: @dog.name), class: "font-bold hover:underline" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeAlone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="bg-slate-600 py-4 px-4 mb-8">
      <% if trainer_signed_in? %>
        <div class="flex flex-row-reverse gap-x-6">
          <span class="text-white font-bold hover:underline"><%= link_to "Sign Out", destroy_trainer_session_path, data: { turbo_method: :delete }%></span>
          <span class="text-white"><%= current_trainer.email %></span>
        </div>
      <% else %>
        <%= link_to "Sign In", new_trainer_session_path, class: "text-white" %>
      <% end %>
    </nav>
    <div class="container mx-auto">
      <% if flash[:notice] %>
        <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative mb-4"><strong class="font-bold"><%= flash[:notice] %></strong></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/training_sessions/_training_step_fields.html.erb
<div class="nested-form-wrapper">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

app/views/training_sessions/index.html.erb
<div class="relative rounded-xl overflow-x-auto shadow-md sm:rounded-lg w-auto">
  <table class="min-w-full">
    <thead class="bg-gray-50">
      <tr>
        <th class="py-4">Dog</th>
        <th class="py-4">Rating</th>
        <th class="py-4">Longest Absence</th>
        <th class="py-4">Started At</th>
        <th class="py-4">Completed At</th>
        <th class="py-4">Steps</th>
      </tr>
    </thead>
  <% @training_sessions.each do |ts| %>
    <tr class="odd:bg-white even:bg-gray-50">
      <td class="p-4"><%= ts.dog.name %></td>
      <td class="p-4"><%= ts.rating %></td>
      <td class="p-4"><%= ts.longest_absence %></td>
      <td class="p-4"><%= ts.started_at %></td>
      <td class="p-4"><%= ts.completed_at %></td>
      <td class="p-4">
        <ul>
        <% ts.training_steps.collect do |tst| %>
          <li><%= tst.description %></li>
        <% end %>
        </ul>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/training_sessions/new.html.erb
<h1 class="text-5xl mb-6"> Creating Training session for <%= @dog.name %></h1>


<!-- We should move the form into a partial -->

<%= form_with model: @training_session, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |form| %>
  <%= form.hidden_field :dog_id, value: @dog.id %>

  Session Steps:
  <template data-nested-form-target="template">
    <%= form.fields_for :training_steps, TrainingStep.new, child_index: 'NEW_RECORD' do |training_steps_form| %>
      <%= render partial: "training_step_fields", locals: { f: training_steps_form }%>
    <% end %>
  </template>


  <%= form.fields_for :training_steps do |training_steps_form| %>
    <%= render partial: "training_step_fields", locals: { f: training_steps_form } %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <div class="my-5">
    <button type="button" data-action="nested-form#add" class="py-2.5 px-5 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100">Add Training Step</button>
  </div>

  <div class="flex gap-x-4">
    <%= link_to "Cancel", dog_path(@dog), class: "text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5" %>
    <%= form.submit "Create New Session", class: "py-2.5 px-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg focus:outline-none" %>
  </div>
<% end %>